services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: chltc_server_container
    hostname: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=chltc_admin_123
    ports:
      - "1433:1433"
    networks:
      - chltc-newsletter-be_app-network
    restart: always

networks:
  chltc-newsletter-be_app-network:
    driver: bridge